os: unstable

environment:
  matrix:
    - builder: cygwin
      platform: x86
             
#    - builder: cygwin 
#      platform: x64

      
branches:
  only:
    - master
    - release


notifications:
  - provider: Slack
    incoming_webhook:
      secure: Ee9fFcoV1ABKmTKowaok5sUiOlRSGzCpWtwNIBFC0PpauqK+/mEt9KjeUXWsb7J7uFcAb1CKo7y/FFhHEJH6pWGMn5oV283uVnqZAB8Chac=
    template: 
       "<{{buildUrl}}|{{projectName}} build {{status}}> on {{commitDate}}:_{{commitMessage}}_\n
        Build: {{buildVersion}} (<{{commitUrl}}|{{commitId}}>)   Author: {{commitAuthor}}\n         
        Download Executable Here:\n
        <https://rawgit.com/RuleWorld/bionetgen/master/BNG_Build_Instructions.html|https://rawgit.com/RuleWorld/bionetgen/master/BNG_Build_Instructions.html>\n
        Build Details:\n
        <{{buildUrl}}|{{buildUrl}}>"


before_build:
  - cmd: ECHO this is batch  %APPVEYOR_ACCOUNT_NAME%
  - uname -a
  - where bash  

  
install:
  - choco install curl
#  - appveyor DownloadFile https://cygwin.com/setup-x86.exe -FileName C:\cygwin\setup-x86.exe
#  - C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P mingw64-i686-gcc-g++ -P mingw64-x86_64-gcc-g++  -P autotools -P autoconf -P autoreconf -P automake -P bison -P libtool -P make -P gettext-devel -P intltool -P libiconv -P pkg-config 
  - if "%builder%"=="cygwin" ( if "%platform%"=="x86"  ( C:\cygwin\setup-x86.exe      -qnNdO -R C:/cygwin   -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup   -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"  ( C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x86"  ( set "PATH=C:\cygwin\bin;%PATH%"   ; set "TRAVIS_OS_NAME=Win32" ))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"  ( set "PATH=C:\cygwin64\bin;%PATH%" ; set "TRAVIS_OS_NAME=Win64"  ))
  - cmd: ECHO %PATH% 


build_script:
  - cd ./bng2 
  - mkdir bindir_nfsim_atomizer
  - bash .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer  %platform%
  - cd   ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate
  - bash .dist_windows.sh %platform%  
  
artifacts:
  - path: './bng2/BioNetGen*.zip'
    name:  BioNetGen
  
  
deploy:
  provider: FTP
  protocol: ftp
  skip_cleanup: true
  host: ftp.midcapsignals.com/midcap/d_appveyor
  username: roberthclark
  password:
    secure: K22E4pSAup6/htlGmoSBMw==  
#  artifact: /BioNetGen.*zip/   
