os: unstable

environment:
  PYTHON: "C:\\Python36-x64"
  matrix:

    - builder: cygwin
      platform: x86
             
    - builder: cygwin 
      platform: x64

      
branches:
  only:
    - master
    - release


notifications:
  - provider: Slack
    incoming_webhook:
      secure: Ee9fFcoV1ABKmTKowaok5sUiOlRSGzCpWtwNIBFC0PpauqK+/mEt9KjeUXWsb7J7uFcAb1CKo7y/FFhHEJH6pWGMn5oV283uVnqZAB8Chac=
    template: 
       "<{{buildUrl}}|{{projectName}} build {{status}}> on {{commitDate}}:_{{commitMessage}}_\n
        Build: {{buildVersion}} (<{{commitUrl}}|{{commitId}}>)   Author: {{commitAuthor}}\n         
        Build Details: <{{buildUrl}}|{{buildUrl}}>"


before_build:
  - cmd: ECHO this is batch  %APPVEYOR_ACCOUNT_NAME%
  - uname -a

  
install:
  - choco install curl
  - if "%builder%"=="cygwin" ( if "%platform%"=="x86"  ( C:\cygwin\setup-x86.exe      -qnNdO -R C:/cygwin   -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup   -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"  ( C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x86"  ( set "PATH=C:\cygwin\bin;%PATH%"   ; set "TRAVIS_OS_NAME=Win32" ))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"  ( set "PATH=C:\cygwin64\bin;%PATH%" ; set "TRAVIS_OS_NAME=Win64"  ))
  - cmd: ECHO %PATH% 


build_script:
  - git submodule init
  - git submodule update
  - cd ./bng2
  - mkdir bin
  - cd ./atomizer/SBMLparser
  - "%PYTHON%\\python.exe -m pip install --user -r ./requirements_win.txt"
  - "%PYTHON%\\python.exe -m pip install --target=. python-libsbml"
  - "%PYTHON%\\python.exe -m PyInstaller ./sbmlTranslator.spec"
  - mv ./dist/sbmlTranslator.exe ../../bin
  - cd ../..
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate --archive --bindir ./bin 
  - "mv ./BioNetGen-2.3.2.tar.gz ./BioNetGen-2.3.2-win-%platform%.tar.gz"

artifacts:
  - path: ./bng2/BioNetGen-2.3.2.tar.gz
    name: bionetgen

deploy:
  - provider: BinTray
    username: jczech
    subject: jczech
    api_key:
      # api key from https://bintray.com/profile/edit
      # encrypted in https://ci.appveyor.com/tools/encrypt
      secure: XzrXGPWsRRrx8DZTJSNJpLkMZrxlXF2vdeao4CCBiXUtKBuxR7Nj2CQIBy3L3bSB
    repo: bionetgen
    package: bionetgen
    version: 1.0
    artifact: bionetgen
    publish: true
    override: true

