os: unstable

environment:
  ftp_password:
    secure: K22E4pSAup6/htlGmoSBMw==
  matrix:
    - builder: cygwin
      platform: x86
             
    - builder: cygwin 
      platform: x64

      
branches:
  only:
    - master
    - release


notifications:
  - provider: Slack
    incoming_webhook:
      secure: Ee9fFcoV1ABKmTKowaok5sUiOlRSGzCpWtwNIBFC0PpauqK+/mEt9KjeUXWsb7J7uFcAb1CKo7y/FFhHEJH6pWGMn5oV283uVnqZAB8Chac=
    template: 
       "<{{buildUrl}}|{{projectName}} build {{status}}> on {{commitDate}}:_{{commitMessage}}_\n
        Build: {{buildVersion}} (<{{commitUrl}}|{{commitId}}>)   Author: {{commitAuthor}}\n         
        Build Details:\n
        <{{buildUrl}}|{{buildUrl}}>"


before_build:
  - cmd: ECHO this is batch  %APPVEYOR_ACCOUNT_NAME%
  - uname -a

  
install:
  - choco install curl
  - if "%builder%"=="cygwin" ( if "%platform%"=="x86"  ( C:\cygwin\setup-x86.exe      -qnNdO -R C:/cygwin   -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup   -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"  ( C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x86"  ( set "PATH=C:\cygwin\bin;%PATH%"   ; set "TRAVIS_OS_NAME=Win32" ))
  - if "%builder%"=="cygwin" ( if "%platform%"=="x64"  ( set "PATH=C:\cygwin64\bin;%PATH%" ; set "TRAVIS_OS_NAME=Win64"  ))
  - cmd: ECHO %PATH% 


build_script:
  - git clone https://github.com/ruleworld/nfsim.git
  - git clone https://github.com/ruleworld/atomizer.git
  - cd ./bng2 
  - mkdir bindir_nfsim_atomizer
  - bash .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer  %platform%   %ftp_password%
  - cd   ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate   --bindir ./bindir_nfsim_atomizer
  - bash .dist_windows.sh %platform%  
  
artifacts:
  - path: './BioNetGen*.zip'
    name:  BioNetGen
  - path: './BioNetGen*.html'
    name:  BioNetGenHTML
  
