os:
  - linux
  - osx


language: c++
sudo: false


env:
  global:
#       FTP_USER_4
    - secure: "nnRgChj9gXsuaX1rjT0E3yAwRCqNxQc/zHw4D93GKW1moD6ulaDQVg4pMpBQuFzbaPe0ne5Ty8yx5lmjSKyrBxgvuT0ntk4y5XYa6hKtCVOaBLeyiYAOc3oi8OTb7OnhGCnTrU4Kk9Jx8y2b62kgphdu5HckpHBbXYPfTUF+kVsdEPRFt9XLZHvAk8c6PWR0FNA7cPrqIYCjlJ4LkeB0woxwtlDRWCAl1KbqwV1wzcDqhv1C8fHHcPNIzzeg68NOt95nWlU9d2Wzn64Ykwopx+45ZHbLIaumWduxYhqVgOPT/6woNsndzVN4Eg3ctM5yvQn0EJ5r3OfhcERwHoFWw1ldsW2tvYv9MtT2SQr/tWp+Qoihsvvp4B6mPZWt7iMTP+Jm2p4NLD7G3HY6eh/BQN88rr92b9qB9MrL1zW1QLvqsnUiOXodzNW2Jq7R1++/1VNnRKceMy4IBLnvvBbbvq2j+2FlUKTgb+uB6boiVNYBqkvbXhgA/zFjCov6i0sCqPaw2QKZoZ0uo1pbYbLhilWf3ccEf/aa6C97qb1byQXj6OYMhxg3o/SPRuLcnwP1pxx1nXAWd517J1JyewfWdNCrZNT8kxa1k4Jhvs2N8ZOFRoAe3WpFYmdvK3AqWzzalmnd+XG3H/Bd3jfkmLkR5p3QZFju4AkzxxNvwn8Unqs="
#       FTP_USER_5
    - secure: "EB/ww9MBLXS2TnFVcbFjR3scG8QsQe7XFyboDTtoXzBL0ks+V9SQjALQQga4adouZeIFDuNm0t3rbJ+/KuM25p/WaheGCa184L6FQt8trqxmHvo4sSvqfMukF0YaCzNKdWkIE0pPTgT9Hb9tkr9b7dqkIWeFiVW1jG/UJijcWKm0dOFXWXyUUKUI6HN37ljPcLJQcO6FNEktqGVxjLzEXaNqcNqi0AgRCKLxsgRv9KEfvcB4dR2pS2n4yWUxDVTp8Yyia2gJxDuF0eA7McU+sfJuPAH58bUw4AyccSvYfHHWnat1pZS7ZuUEewEQpbvXgHwQnf92qTSqCIcWOTj5H+SF/6c3QtwOJRgdj19evo0CXFzcgmCIkrE3cPkReP4usKlBjS8BCjHm+cvK0IPSoq6tTtSQcmckid8YKSRCffXz3gXPdqjjDyrYCB60L8PycvL2vHQCgw6zfmgfggc3SoaLiGMfslv+HFXFcXDqEMn1UNz9GqEcqfEyhfqEmjykwOX572UBEp1TnVmtyS9piAKTPhso32wyGIMcms7Ohk/tNkC0Kphu6xHwL+x/Xq/WW45FmZfwjBNU4zI/8Gdxq5AIbYNqqvM172QLl8Jh0imIPOnfZI6wKFraAy3CUQhpRQ1K+Onrb4eh17oukqilkISbgfYYO6r7Oyv2CChCpK4="
#       FTP_PASSWORD
    - secure: "k4LDmoek9euxvKB39fBugp4f4M4hFtuNfC9HL9ei6WcgnD5An0XJP4+nW4qJLpPYnNtdrPlmP21qv2UTO6CijKjuHhsrM0Bbf4vyI1I+QAoxY/mc5iyYTSe+CtHQY/GznsZLzfEtkxE8wGc028/RSof1sn1y2M6bMDw9J5RQvUS8WYmTORcdzDppSWwjMbkofTTabyhrnz+5Eg8xKW7Az1CwIpOGTXq2BDMkMGfwmMRWcKrPKmuHLX31mX7FFiDoKR72I/T8cKSwPcZJ8jR7bXWuRM9rsX/kEQTybM8PQD9COxIV5tdmzJ09asCCeAIDq7VC+TCpvfieKCOZH9wz6sqfLbG8NIAcakcF2/pb2vb5L8c1yIgrUpbSjTzD/+IpMzdkoHoAK28BJETIZOTQf4vykA5gxTQoeO6l3Yt4cWagnL31Pm1bjAt+zz441EStNiXk3S7oyjwgb7TM571BjXAZ8UXr+OfLMl4gSWtNiEKXjq+KmYG0EoMkG6AM4r3IIFQKj5CJs8BWl3l3gI4fdSx7sy12pMqVMSxeQLwGwabAHZnOjlPF1sTzi8t5GdkHsZHT6DTMkiEoOkt6L+lcUsm3SQvju+QfALJvlbHjq1A8TJLPZjsOjWnC5/u9Fe8ysICA0ie4DzJoKoL9ol361+HeZ7C4OGhX2i9I6wP/2D8="

#       FAEDER_USER
    - secure: "stAZ+q/O0t3Js0IlyuNId53vGcDGZkvwDIXlXixB/OCqcE5t4lb+WT0pZtzs46wi9+0R2rXwyxmU1qpZkBGdPGJN4BtPTjf19X/CFLn5uBPV4fwgRQrnmYS8ShSnzUHziK9XZ91TUP8VkMJnwwLmmNwBUq5/DB94NdE7vhJ/zQIKIB6vVJpFQTMyHDPzjrRQNcrgBBso+/+hXpgr6wKvbTV+714PoQTr3+CsUhS5IPJUCeOMCo+9CGU6qbprDPMgkmDkQYTSHqz6gNW5zgEkX2IW8RJmthV/yhaw3bu+m7q8ZheD/fv3cjkUbr6qL4FdO1yz8TbKTbyY8bApEA7yDss2BwATHmKwC3x7FciksRiU3GdV7gumsjpq2Fn+7rxNYNmKDRgIq0CnoPKw4AUM89bFszeRdw+RthYzEScNkFWO++CtAtbhL8/brow1Ck6/Fl/W4/LaDdrZiY1REnHCBaf7DYIj8cF8ObomT0lagtXEKd0jwbqRqE7vCxahZPucvFD3cDHynfzCgGuSvq2vTgeCL1ndQFAL4AbhaHFWD9SjVhks9wGwZu9w0/N/dOy2VQJahkuzdSJqaobYFCLitv2BYanY5PCdNVI3ixOhXqHVWQ8ScubMXhGShgQcf3U8b5I+UCnRwecOp4l6JrrmSfvDxFrQCMrAar7WtihGxI8="
#       FAEDER_PASSWORD
    - secure: "Blt7cHDdvHfv15MOVFA66/N++Z3PmXsdzra5JCpP0SFMHdOCka6QlP7VUTBSylDO3KF1UJqDiqUEI8aQUWGKtBZw+smVE2Ycvf7rSOgWrS51qIbr2QvuQKRaki6bhvBY2UGCF1R+X0KAZcELnwN+bWgiSxhsK2aJTDy9uwC7ZGok+lsYFD3OrA/A5BDUo4EdALyBb7cJlM5rpv67grVfQDMP97M/lipARhWPp6xIey+Omz9nE9HBPWHwd9cTEwjw5uKVIZxAqyjal7NPakZ90v9BdtKQPFyzC8JhIF7omJUzBACAHpLvHZHAbCxsF2fKGsjn7J6tX5sp5N53jLjL6V8+LSbkKkrT0y+ZeRFLLMQQlOrHtApgeM3onpESgVrMzCWO0HA7eQzrq4dwemQYiy92PpsUjqo5lBByo6ecmrtgbxpRSCrMXnHA1Ll3MUbxe/0geGGcvfkqR1mUHNJX/xcrIWl31vGCM8WQkI7QKoq9is97U9fK6aLHHhTp4Wj5N8bX13EDOTrdUECb80DqnB2tLl+jo0OtA0X2yIM7oONX9ofUAxwU4oJtj4FVLyO32gR8oniweAnHJs7H4FDW//N37w53W8Uch7ioy+wrifmPgrML00yarMwNzXWdg3zJasaXa/zU80JmwbmgufNOUI9M5rYT1u1m0Z0GpqrQzaU="



notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Download Distribution Package Here:"
       - "https://rawgit.com/RuleWorld/bionetgen/master/.BioNetGen_Beta.html"
       - "Build details:  %{build_url} "
   
  
script:
  -  cd ./bng2
  - mkdir bindir_nfsim_atomizer
  - source .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate  --bindir ./bindir_nfsim_atomizer
  - source .dist_unix.sh


after_success:
#  The make clean step has been added to make_dist.pl
#  -  cd BioNetGen-2.3.0/Network3 && make clean && cd ../../.. && mkdir dist && mv ./bng2/BioNetGen-2.3.0 ./dist/$TRAVIS_OS_NAME && cd dist && tar cf $TRAVIS_OS_NAME.tar $TRAVIS_OS_NAME && gzip $TRAVIS_OS_NAME.tar && rm -rf $TRAVIS_OS_NAME && cd ..


