os:
  - linux
#  - osx


language: c++
sudo: false


env:
  global:
    - secure: "ifMdh+XG3tYjLP65ASs9REcCBCLIaYCRda3pDbuoGACEpyqaEyTAbu5D/kVRZS58gUOOGDqZEgeA0qghbWAV1suEVfrkXTkJHkG7B+4kAUDmaeo210oMYBKM+KcMxsYNSU2uemn8QDdxbHj0z51OZmzkmEUiLmSxovETn5XAf5OlaPmn67MujC/ZxKrrpwhOSZjx/gzXkrsWnx1MJxH484EjJEClpBLSExy6mrEDXMflOt6PivJpmCenwTsZkIw3GqK0OYT8D2rY4RxzvSkXQqHCrjDQbHKerrSVFdaK9KrDo1Gs/QlGnFlPmaROudd/lYH/JDSloha8K/4t1wzXP+zAgKKFOVDl6E1STPlUlkRFY7JyCRkr38Zxw3078KyZKH1Qpqh2whQwUXUD7Ao346X39hV5IOLTeATYA39JcIVjDoHIGlwvr6RwDBmCfWq8dtupOCakWeHiBjfKFt5uAtF6tVpp04PodtCeCKZ+/i0Zpmwejh/WTMwxmwsox+gUwL++Yx+DEycb8dfPMQqfncEcgMV5iaCuL0ZqndqxywPyocXHnIMxwJxNUutTgpyPSAQB1DWDNgg7UsatNZVkoH/uzwuQJ4JPKf2COPGdr2fST3/PYVpMJXTtmCd7Os3AG3KkB49DdKso7e/DRLcZ77KgUmAxMA/q2gLrY1Ts9O0="
    - secure: "fpYWuT8BKkZpFjNzq2Jm1XWnZUV/rdOY+FBtIe8jlQnSobhcHODNGWgHYXKxInWAyMx0sBXh4FxWU0xWl5pdSsp15s5ObnDgAFaQVOCEFNxnY49pCcgTP2Gas3Qugbk/sr/edvwK98AijrITyuxu5Mz8NZzCE4EzbJvTloPhS8UetenzSn+SED5jjyOc7xH1RmW9gukmI5DCIVvAZMV3Lr3/m4EobX/WzO2IAi8Gm5e3Cy9HdkQg3uh827t1oMmhwdilbAsithvRRpBKyyHxfYA28j6fVldZqr2HZTlpj0dRHAKL+0UZsp4KmhG+GT+Ct49+NlY368YyqItRYi4A0Iou1zOiukZKgPqMXACyOzXiEPul6stftGSLcLsuGib+QORX0nkEMGx9aSESesn6xeoCluUpWL7H3/GecB2kFrGRMdJlieZOS/s9rP4aJIyONCKfAfEp7lOLFnO7m5yrY+gJciiSOZxLPdLBm8+9B3fuOOEVn3TyN0E2fX7DVmwM+Fki05bMssdz8/MejcGXWj9g+CXjAtsnprtf+3PTDmNwKYXX4WBi918wk0/sQB7Qoy0HtlIltbxrh7kYsEQaA7922POaGtLWA8t/oFuGwUGmkgqsw2tG86eNieW4mXKULx8hb7DOZvwsIGStzmvaOU7lsCKMPbhfpGx1G6Q3l0I="
#       FTP_USER_0
    - secure: "qqHAeQz9NJf64xKxfwpE5ZqSOV++UB6PWLhvUNcDg8/WJAlxy5Fboi3YUKRDqRRhVpmipqyalwEy9ALzsoL6Maj0OoPcUzCuumBS7Ts1svNOORp2gZyRgUbZVUkAZ8VET8WhNrcN02TiR7NBvbjf/IFElpfOXVXMD78tDwhJlqVS0yxKXlnuI7m3yf9LhcA4Y+M8e8yD/5uqVFLdufoNLTNyqx9ftQeYwpG/PPDx4T9ciSto/8NGE2LjfamC0TqpySmjKdwYAYkYeBkIO0GgA72/C8BgKaF+OsUaNhycWDDxUx6DftPkfYw7PsqZWOBWkbNGqr0QZJor7MxJtvs+KGkLNseAznUmk1ETYqrIV+WalzDfT9yQ/8dELzAE1GZYoj5N5M+2Ltj0cjsZLU6iud68xD9epWWSQdW6TsyDTQWt5QonKmf7/daU0BnhkKmfgECL2qnhFeQIizMvryauQ3eC5zU1cYFlty1q5QN6OEf0jLmXsuBc0pf13PaPc0mDhXe04w+XF3aq2tC4W1Z5hdVfkpJxaql0WzIHdC1PpmsebbX8I7HcG26f1IfN+hkdRNy3HF7wBnGFjUSbe2Hw/sXLeH1E8R3P6NQJj0rWT8sbVy9JSjw/dkuTCYblHWKaHNl5yWc08UkWQwWwPiKZlRcA0OX/RaXJNtbL30vOuVQ="
#       FTP_USER_1
    - secure: "mgaOToeGS1W2Vl605SiG7Vjc8yRPA2CwowHf/YbR2m8WNjB88VgO9bwXYTNl+Szv+D8EnCzTaY3fZSajqpDSHEMIk3QttqMAT/rJZVlbVKW8GxGj1Or8H+PTAKoE9zwPbxBgwC8esNmgTuMeesjsP/zciofwH0oL0Q6BOupY+AUKGd9WhUXquayjLZ1D9RXfrHBDxGV2+fSykZN25o9MwGvW47ak9zSpUwILVWw4+VDEpGaZzzisGo/d9k0aOXi3H8PlVW0JT+C0khh9zNiyq02ovWYOAZw+d1i+jHYMhvn8Xt9u3aWG9ewMASA8lQ9HD09C7LDnJA1hUme02GaZCIvZEW7GOgUAhyqGRylvV0TEnMIyk/9J2Q8EFDo/gHqXlUsU9+IQ3TIUm7m4BWgOweuXxZ07KuNvZVwL4m0oH9K3eKD5SQY4tqSAzyzO43xFUCZlgv9IRzktANy9FKBweKDinucTKN9fvKBiVX0aD01fFPzYIwa/aAOQwx4M119pPe0iH2+C1uG4N/1OMRM3f8a3QlKthFbXD/WHb/IyUzhJpS8b0JPJBFoP42wPtDFCc5MGvBVdqqirKwtgihd6SkR+HKn7LeyrL6IK9Ud+GnLM8ouifx2AoUTWoBapQCIbiJTHs8M1nFKS0aqXPv9sLVN6ujxQJcu+qGA7gynIO3w="    
#       FTP_PASSWORD
    - secure: "k4LDmoek9euxvKB39fBugp4f4M4hFtuNfC9HL9ei6WcgnD5An0XJP4+nW4qJLpPYnNtdrPlmP21qv2UTO6CijKjuHhsrM0Bbf4vyI1I+QAoxY/mc5iyYTSe+CtHQY/GznsZLzfEtkxE8wGc028/RSof1sn1y2M6bMDw9J5RQvUS8WYmTORcdzDppSWwjMbkofTTabyhrnz+5Eg8xKW7Az1CwIpOGTXq2BDMkMGfwmMRWcKrPKmuHLX31mX7FFiDoKR72I/T8cKSwPcZJ8jR7bXWuRM9rsX/kEQTybM8PQD9COxIV5tdmzJ09asCCeAIDq7VC+TCpvfieKCOZH9wz6sqfLbG8NIAcakcF2/pb2vb5L8c1yIgrUpbSjTzD/+IpMzdkoHoAK28BJETIZOTQf4vykA5gxTQoeO6l3Yt4cWagnL31Pm1bjAt+zz441EStNiXk3S7oyjwgb7TM571BjXAZ8UXr+OfLMl4gSWtNiEKXjq+KmYG0EoMkG6AM4r3IIFQKj5CJs8BWl3l3gI4fdSx7sy12pMqVMSxeQLwGwabAHZnOjlPF1sTzi8t5GdkHsZHT6DTMkiEoOkt6L+lcUsm3SQvju+QfALJvlbHjq1A8TJLPZjsOjWnC5/u9Fe8ysICA0ie4DzJoKoL9ol361+HeZ7C4OGhX2i9I6wP/2D8="






notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Download Distribution Package Here:"
       - "https://rawgit.com/RuleWorld/bionetgen/master/BNG_Build_Instructions.html"
       - "Build details:  %{build_url} "
   
  
script:
  - cd ./bng2
  - mkdir bindir_nfsim_atomizer
  - source .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate  --bindir ./bindir_nfsim_atomizer


after_success:
#  The make clean step has been added to make_dist.pl
#  - cd BioNetGen-2.3.0/Network3 && make clean && cd ../../.. && mkdir dist && mv ./bng2/BioNetGen-2.3.0 ./dist/$TRAVIS_OS_NAME && cd dist && tar cf $TRAVIS_OS_NAME.tar $TRAVIS_OS_NAME && gzip $TRAVIS_OS_NAME.tar && rm -rf $TRAVIS_OS_NAME && cd ..
  - source .dist_unix.sh


