os:
  - linux
  - osx


language: c++
sudo: false


env:
  global:
#    - secure: "ifMdh+XG3tYjLP65ASs9REcCBCLIaYCRda3pDbuoGACEpyqaEyTAbu5D/kVRZS58gUOOGDqZEgeA0qghbWAV1suEVfrkXTkJHkG7B+4kAUDmaeo210oMYBKM+KcMxsYNSU2uemn8QDdxbHj0z51OZmzkmEUiLmSxovETn5XAf5OlaPmn67MujC/ZxKrrpwhOSZjx/gzXkrsWnx1MJxH484EjJEClpBLSExy6mrEDXMflOt6PivJpmCenwTsZkIw3GqK0OYT8D2rY4RxzvSkXQqHCrjDQbHKerrSVFdaK9KrDo1Gs/QlGnFlPmaROudd/lYH/JDSloha8K/4t1wzXP+zAgKKFOVDl6E1STPlUlkRFY7JyCRkr38Zxw3078KyZKH1Qpqh2whQwUXUD7Ao346X39hV5IOLTeATYA39JcIVjDoHIGlwvr6RwDBmCfWq8dtupOCakWeHiBjfKFt5uAtF6tVpp04PodtCeCKZ+/i0Zpmwejh/WTMwxmwsox+gUwL++Yx+DEycb8dfPMQqfncEcgMV5iaCuL0ZqndqxywPyocXHnIMxwJxNUutTgpyPSAQB1DWDNgg7UsatNZVkoH/uzwuQJ4JPKf2COPGdr2fST3/PYVpMJXTtmCd7Os3AG3KkB49DdKso7e/DRLcZ77KgUmAxMA/q2gLrY1Ts9O0="
#    - secure: "fpYWuT8BKkZpFjNzq2Jm1XWnZUV/rdOY+FBtIe8jlQnSobhcHODNGWgHYXKxInWAyMx0sBXh4FxWU0xWl5pdSsp15s5ObnDgAFaQVOCEFNxnY49pCcgTP2Gas3Qugbk/sr/edvwK98AijrITyuxu5Mz8NZzCE4EzbJvTloPhS8UetenzSn+SED5jjyOc7xH1RmW9gukmI5DCIVvAZMV3Lr3/m4EobX/WzO2IAi8Gm5e3Cy9HdkQg3uh827t1oMmhwdilbAsithvRRpBKyyHxfYA28j6fVldZqr2HZTlpj0dRHAKL+0UZsp4KmhG+GT+Ct49+NlY368YyqItRYi4A0Iou1zOiukZKgPqMXACyOzXiEPul6stftGSLcLsuGib+QORX0nkEMGx9aSESesn6xeoCluUpWL7H3/GecB2kFrGRMdJlieZOS/s9rP4aJIyONCKfAfEp7lOLFnO7m5yrY+gJciiSOZxLPdLBm8+9B3fuOOEVn3TyN0E2fX7DVmwM+Fki05bMssdz8/MejcGXWj9g+CXjAtsnprtf+3PTDmNwKYXX4WBi918wk0/sQB7Qoy0HtlIltbxrh7kYsEQaA7922POaGtLWA8t/oFuGwUGmkgqsw2tG86eNieW4mXKULx8hb7DOZvwsIGStzmvaOU7lsCKMPbhfpGx1G6Q3l0I="
#       FTP_USER_0
    - secure: "hnGm8cr+5yBAl4k4XUyMpmiePMDp6JJPOBcZYcDOdmCjALkdtC1OVUmLhe6fbCAZ/efF4P6qBid/S3Qk/OjfUMMYAxhpqTMx3IYFnxktUR2mRlmua9zGbCAGRQ7eF7EcdpwIHv5qUlHmb8NTqD6T5GHL+822pmcQE/mPZkyvuqjFOVYO88fDRF87jIYmIUQRqCCUSkn2OVKx9l58G33H8T3qVyibykJyerSSgZx3CxOtmSb8cn1n6c+APCFL/ACiegskd5GdcZsBZXqCo+EgBe2z4iaLeo+9Blopi3hJln5rT4xmnDbJTdGLUp0IarXrZWY/qibT7X74aoyfW575AFqWRkIhRvCKtAjdxbru6ESwWdbcnXUrg8lClxoLJMq88GXuyiqT2dukrBGVe7Oma0gv5AleOOlX0sC2WhX+Zu2WtUZud0vbxGGdCqWXVZdyRUiGXaZI89imonMBQvKso3vobQFdCM6AdsyM+Dn5eKlifYyerfjZS1IYgPYYLGdjBU7aMvacavyxMHR2mMtS8ZH0SgrhV1VoxoBi7SdBPsUOo7oquQzxkSzopE5OYy/cIaK4fiaQlxmP+zQg87pvQmptaYigHLTntJ4UkQExgjOFuYH08I09plYmShrVV1jQXIIEvOKF473B7sKJhro2xqbXu+h8wl90b/ck7XkrPhM="
#       FTP_USER_1
    - secure: "jDCJH/4LWXIaYrbpOyoBmdg1YTvfqaUhD+mWbHL6SKYKdTEG+qYO5f0sz8LXcEcZYTYc5SP/2jS9wMO5eOFv+m8yJIqkd0gwc1rvwSO/vFhgISEVw2CCK+12edtFWrSi92eKWwqy+6RMmp6uAIYjZuqXTm+LjXOsxdBfVcuCve7UAJjRzTGEFKKeiC+fZZxZxG6LQ+BwDzJ2lElyB4CSVO4Z0euoW+p5aoT6zWsyRPL9STY+mqaAJt9pl3EQ+Sf3fkyJx7mIjm4VDmmfN8Dg8xdsqJwr6GZQMisEATewWInsGI+rvtDchG5ojWGgnY1/D2on5Cp8D+BRQXBd0e1PrWC6XTgifATh/mB0iKK9eCUph1vqTa52Kga9htaCJ0ZEfQRI0DhXtbgmmcEhxMjl35kbwIaLoT69UCU0S1dRLtqoMHUu2rC/76stjVaB+Dq7DiNjYfPnsY1g7+9hNgjWUJz3y9VIlD/YmXpcZI5VJIF+OT3k/FTqFh5pG3hjBaUEsVp5VLoV5PvQ9GfThVKWSLYrdWJ1oTIUZjcEfU1nxV6+N61QhYk9x+A+L3bOO5gfsLfps6J4esbbzHdxQAOD7+rBy6w8o3YyrDWADyZ/sa3xI79qjGFmKv9/81butkyo31HbYgDqD22jp8EbFUEvClPB+zPLQzIJF7jOjtU2a9c="    
#       FTP_PASSWORD
    - secure: "k4LDmoek9euxvKB39fBugp4f4M4hFtuNfC9HL9ei6WcgnD5An0XJP4+nW4qJLpPYnNtdrPlmP21qv2UTO6CijKjuHhsrM0Bbf4vyI1I+QAoxY/mc5iyYTSe+CtHQY/GznsZLzfEtkxE8wGc028/RSof1sn1y2M6bMDw9J5RQvUS8WYmTORcdzDppSWwjMbkofTTabyhrnz+5Eg8xKW7Az1CwIpOGTXq2BDMkMGfwmMRWcKrPKmuHLX31mX7FFiDoKR72I/T8cKSwPcZJ8jR7bXWuRM9rsX/kEQTybM8PQD9COxIV5tdmzJ09asCCeAIDq7VC+TCpvfieKCOZH9wz6sqfLbG8NIAcakcF2/pb2vb5L8c1yIgrUpbSjTzD/+IpMzdkoHoAK28BJETIZOTQf4vykA5gxTQoeO6l3Yt4cWagnL31Pm1bjAt+zz441EStNiXk3S7oyjwgb7TM571BjXAZ8UXr+OfLMl4gSWtNiEKXjq+KmYG0EoMkG6AM4r3IIFQKj5CJs8BWl3l3gI4fdSx7sy12pMqVMSxeQLwGwabAHZnOjlPF1sTzi8t5GdkHsZHT6DTMkiEoOkt6L+lcUsm3SQvju+QfALJvlbHjq1A8TJLPZjsOjWnC5/u9Fe8ysICA0ie4DzJoKoL9ol361+HeZ7C4OGhX2i9I6wP/2D8="






notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Download Distribution Package Here:"
       - "https://rawgit.com/RuleWorld/bionetgen/master/BNG_Build_Instructions.html"
       - "Build details:  %{build_url} "
   
  
script:
  - cd ./bng2
  - mkdir bindir_nfsim_atomizer
  - source .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate  --bindir ./bindir_nfsim_atomizer


after_success:
#  The make clean step has been added to make_dist.pl
#  - cd BioNetGen-2.3.0/Network3 && make clean && cd ../../.. && mkdir dist && mv ./bng2/BioNetGen-2.3.0 ./dist/$TRAVIS_OS_NAME && cd dist && tar cf $TRAVIS_OS_NAME.tar $TRAVIS_OS_NAME && gzip $TRAVIS_OS_NAME.tar && rm -rf $TRAVIS_OS_NAME && cd ..
  - source .dist_unix.sh


