os:
  - linux
language: c++
sudo: false
addons:
  apt:
    packages:
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - python-lxml
compiler:
  - gcc
before_install: 
 - pip install --user pyyaml
 - pip install --user networkx==1.9.1
 - pip install --user pexpect==3.3
 - pip install --user python-libsbml

notifications:
  slack: faederlab:ihDgCLMiQw3hdS63HuzJ2aYs
after_failure: 
  "cat /home/travis/build/RuleWorld/bionetgen/bng2/BioNetGen-2.2.6-stable/Validate/test_sbml_flat.log"  
script: cd ./bng2/Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate
