os:
  - linux
  - osx


language: c++
sudo: false


env:
  global:
#       FTP_USER
    - secure: "mA1TI0621ZyQJcAlLz5YJ5kPrv/1mCZVIpEME4UnsU+TJWGO5m5GxxKC/Xe5httZbKTOZAttz2vy421mJvgv4rAvaUyp8Y3sLhZsgs+peAm7dEApyouyn7Cd4R+vmUG+yHlvYyJqiU1J2g1/Bw8Vcxijg7MHi1nmpqMfvm9DnqcFkZkq/n5jVNGEc8dUZDUQsxb6qbk9qC3Kga5ZJScvxmFlHTGz1920P/7PdqXyl3aQMiAOgRJsOw/1WWNrem2B8ZGBcnM5aQhQdY9h4LMdZVYBuZuHEhp2i/ljfu7m9FkNzQ7cCVXMevgL2lzi6cZz/8flHt56G2/vHNEukJsxCBl8TRSf354aOrpQsWzAk+4FkOfZcVTGVyDgsmUZLY0n04JdDkytXZe6uNAoG22A0q0k++nXK4RR6pOCIbaguVqmJUtOz3x6qK3ogRAAd3L3jWLonPIRugMxygtgifKU+VQoAS+T2uyeXOeViXQtyh7MAsAKGjMhlA4tKTnkkRLshTR6PGAVBB29+mqXjJHo2+j1iLApUo68YjK2n9jiwD9LBjWta0wwh0sk/Xe2+xR1LaFZ3EB+AMDRbw0xMzLbShLUZtnB0NscZtalJlFGF3jkysrhneIliBhebIHGZNmXXz01/S6j9YdBvGAtKSkOTbWKwl1GpwRCn1U7yl/hZT8="
#       FTP_PASSWORD
    - secure: "fFNopgC7z7FeeKeLGCcfLJDFV8/+P7bdoNYoSGn6LhtFxQAjhBFP9YDJbn3dTyB8X2iXzYnvr6UwONxwIZ9kpIXP24mOKsrty4/yuXeRkk9SWIlZZXpQrSnQJ+cuDCSPNWhpn5HkN6iTgX+0eBPYSVgWnwpjS2NlxilN0jYPuXyRvPIZQ9xA20Y4cArnuE+8jOmzWjDcLyYwDod2LXB+eDG6eAHfGyhUxCHqvHTWeVI1G+CsW9jMBNCd9gRgfCO9Cxz/L97pmKX+j8S1VjUqWXr3X1/LQRbqxC9EEu6x/i1otB/6FJksOu40ZlDUrDO0VTyOgK5DkJgNGQHh3kUVICY7PVcAKXR1CmmwJ8x/lsr1xt3JAYKBWFed15cEEXVNGwBMh/jcJMna+dcynHpZZS8z1SYTkKJputMzUCZvCgprhK9g2rjwr+MxrQufTQFEb3W7Jopz/DH+3J6KjFKN9luG5eRzurWtBp9sfLyafkKq2MQ20Ry2qtJJNyiD3GHChUnYbUNpWvFM1Ok1oRrAMAbWaDRzbMLSUKhm907WsTO20Y7txAjtF12ucqRL8iNnb6PtyfWTp5kld5D4BY+BFstrqj/rDU8Z/ozEfnx9RJbrQl+Mh0L0zs5k63BX9TRMBMqY7vDUL7pJQRwdXAMMbIKYiSY74AvV9QhoV2nGoBE="


#       FAEDER_USER
    - secure: "MnA/A2IS7y0sN5+IrJ7rxfFtFl9GagP6hlvzz4LHZG1lXn4Du6QdMwaJZ6OJuyj9hKuuI6YsCf9Zr4dzjemzjWJwLZN4hkL/fJ44rNvU1HDe6QKcSSadEGknndntNQVM9z8LuCpFxhuJmZ3hSWFJVifo943n4HtYko1/NvGWVYQdGf8mDGXtcxu7QF/+kMkOXYTNYb3XtTSX2augEXFuwbAW7XStOs+Y+WiHuHGn+1H3W1fviSIVkUEKMNKPXwBUVfJWHdaYH9PLjjAFokYhE1W6wJLXUBHy5T8D1mLroivqUKMBQIJG6PE2yd08vBm8H2zjOOTyW5YaMo6OqoFaB5tYEBvjATuJ9NbudIysvb1iN5Enriks8BlfTeEqZRGpL8eFPeSilm/FNNkFT2eyXoqmDXtdrtPr/pPLIS277KTMQ7WMuwpJm/ToysGoD3ELlynW62vHo6NtcSNY3x9+QZA1NR37MOR2nFLZ3PlvKzr/KHEq7/XkpFVvW8GD9OsOUWPxpjEdoKs/ZiHKjUvCe2oRgp8PHhmgOoQe8aAYWydJ7Fm0Ykq+bnrdjpDQzPOs7uFBDCaHHRfb9d3i2AfR/sJe4HSnV0Wdsb1im3nrR7lWNuZU+FED+wbwsUov2YymeWb5SmCTW1GFWqD0uMfajXJBw/nUIVZklc/ZwL51fRc="
#       FAEDER_PASSWORD
    - secure: "qBDMRX0s+cE5ersr6XokpWYa/cLGndUA18+n3AjDQOOyRM+PGs3tz/pbx4pky3cws6BdMQ7LwQh2cjp8gFbvvSXBl8y70pYryS5DiCRYVlcUGMqXIobaYhJ3NBfSxm2RXiGdathX4yLWywixhL3pkmIxl+LtU/9mu2O5MemTqGySfJMxBA6U4FJRDcifsYxcLuySYlYJIpQs7b4qMAuM1jQVTbFT/Vuisz0rW4UlFr64oZhIpeow3DBBunIu97ZxLMJtwr60bifb26O2l7N9Duu6Kfy2uu/4tVCKju/KImhQMsnZhPtH6WG4i2ycWYuTRmxuctNp/1rsVOdAsQ8HmZHPTXg25DdTttsKUG7pcW1FV3WYemlrOSUlM+Rl9Ze6faQ5sucbRbE0svDmzYnGAY70yn72ekKCV/YEdOO3FTOUlatQ6c0BGK5+TMKE0CHkVNQLUQzx8uXfNRLVRuAoNknlvBjtHYtphK/oPtuw8ID1oYDUdTAxtuMjxKlC1dEETq4fWFcTz/zHXA4PC/QuRf4HIVX6xHcbtuF2Ks2ZLH/hMHNuaSrOYNeUqXLm8GjA6xwYgEDxeEr0TRQG3dKGiAsv4I2Ozh5oQcYGPipjmc3ID7qvvTueMRHsbicNRFPO2h5UROGTX/ki9GqKGgzIEbdJcW0uQp3z9/qtMHaC/Lw="



notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Download Distribution Package Here:"
       - "https://rawgit.com/RuleWorld/bionetgen/master/.BioNetGen_Beta.html"
       - "Build details:  %{build_url} "
   
  
script:
  -  cd ./bng2
  - mkdir bindir_nfsim_atomizer
  - source .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate  --bindir ./bindir_nfsim_atomizer
  - source .dist_unix.sh


after_success:
#  The make clean step has been added to make_dist.pl
#  -  cd BioNetGen-2.3.0/Network3 && make clean && cd ../../.. && mkdir dist && mv ./bng2/BioNetGen-2.3.0 ./dist/$TRAVIS_OS_NAME && cd dist && tar cf $TRAVIS_OS_NAME.tar $TRAVIS_OS_NAME && gzip $TRAVIS_OS_NAME.tar && rm -rf $TRAVIS_OS_NAME && cd ..


