os:
  - linux
  - osx


language: c++
sudo: false


env:
  global:
#       FTP_USER_4
    - secure: "nnRgChj9gXsuaX1rjT0E3yAwRCqNxQc/zHw4D93GKW1moD6ulaDQVg4pMpBQuFzbaPe0ne5Ty8yx5lmjSKyrBxgvuT0ntk4y5XYa6hKtCVOaBLeyiYAOc3oi8OTb7OnhGCnTrU4Kk9Jx8y2b62kgphdu5HckpHBbXYPfTUF+kVsdEPRFt9XLZHvAk8c6PWR0FNA7cPrqIYCjlJ4LkeB0woxwtlDRWCAl1KbqwV1wzcDqhv1C8fHHcPNIzzeg68NOt95nWlU9d2Wzn64Ykwopx+45ZHbLIaumWduxYhqVgOPT/6woNsndzVN4Eg3ctM5yvQn0EJ5r3OfhcERwHoFWw1ldsW2tvYv9MtT2SQr/tWp+Qoihsvvp4B6mPZWt7iMTP+Jm2p4NLD7G3HY6eh/BQN88rr92b9qB9MrL1zW1QLvqsnUiOXodzNW2Jq7R1++/1VNnRKceMy4IBLnvvBbbvq2j+2FlUKTgb+uB6boiVNYBqkvbXhgA/zFjCov6i0sCqPaw2QKZoZ0uo1pbYbLhilWf3ccEf/aa6C97qb1byQXj6OYMhxg3o/SPRuLcnwP1pxx1nXAWd517J1JyewfWdNCrZNT8kxa1k4Jhvs2N8ZOFRoAe3WpFYmdvK3AqWzzalmnd+XG3H/Bd3jfkmLkR5p3QZFju4AkzxxNvwn8Unqs="
#       FTP_USER_5
    - secure: "EB/ww9MBLXS2TnFVcbFjR3scG8QsQe7XFyboDTtoXzBL0ks+V9SQjALQQga4adouZeIFDuNm0t3rbJ+/KuM25p/WaheGCa184L6FQt8trqxmHvo4sSvqfMukF0YaCzNKdWkIE0pPTgT9Hb9tkr9b7dqkIWeFiVW1jG/UJijcWKm0dOFXWXyUUKUI6HN37ljPcLJQcO6FNEktqGVxjLzEXaNqcNqi0AgRCKLxsgRv9KEfvcB4dR2pS2n4yWUxDVTp8Yyia2gJxDuF0eA7McU+sfJuPAH58bUw4AyccSvYfHHWnat1pZS7ZuUEewEQpbvXgHwQnf92qTSqCIcWOTj5H+SF/6c3QtwOJRgdj19evo0CXFzcgmCIkrE3cPkReP4usKlBjS8BCjHm+cvK0IPSoq6tTtSQcmckid8YKSRCffXz3gXPdqjjDyrYCB60L8PycvL2vHQCgw6zfmgfggc3SoaLiGMfslv+HFXFcXDqEMn1UNz9GqEcqfEyhfqEmjykwOX572UBEp1TnVmtyS9piAKTPhso32wyGIMcms7Ohk/tNkC0Kphu6xHwL+x/Xq/WW45FmZfwjBNU4zI/8Gdxq5AIbYNqqvM172QLl8Jh0imIPOnfZI6wKFraAy3CUQhpRQ1K+Onrb4eh17oukqilkISbgfYYO6r7Oyv2CChCpK4="
#       FTP_PASSWORD
    - secure: "k4LDmoek9euxvKB39fBugp4f4M4hFtuNfC9HL9ei6WcgnD5An0XJP4+nW4qJLpPYnNtdrPlmP21qv2UTO6CijKjuHhsrM0Bbf4vyI1I+QAoxY/mc5iyYTSe+CtHQY/GznsZLzfEtkxE8wGc028/RSof1sn1y2M6bMDw9J5RQvUS8WYmTORcdzDppSWwjMbkofTTabyhrnz+5Eg8xKW7Az1CwIpOGTXq2BDMkMGfwmMRWcKrPKmuHLX31mX7FFiDoKR72I/T8cKSwPcZJ8jR7bXWuRM9rsX/kEQTybM8PQD9COxIV5tdmzJ09asCCeAIDq7VC+TCpvfieKCOZH9wz6sqfLbG8NIAcakcF2/pb2vb5L8c1yIgrUpbSjTzD/+IpMzdkoHoAK28BJETIZOTQf4vykA5gxTQoeO6l3Yt4cWagnL31Pm1bjAt+zz441EStNiXk3S7oyjwgb7TM571BjXAZ8UXr+OfLMl4gSWtNiEKXjq+KmYG0EoMkG6AM4r3IIFQKj5CJs8BWl3l3gI4fdSx7sy12pMqVMSxeQLwGwabAHZnOjlPF1sTzi8t5GdkHsZHT6DTMkiEoOkt6L+lcUsm3SQvju+QfALJvlbHjq1A8TJLPZjsOjWnC5/u9Fe8ysICA0ie4DzJoKoL9ol361+HeZ7C4OGhX2i9I6wP/2D8="

#       FAEDER_USER
    - secure: "GcHmz+7y5qvcJUl76nGPjEt+yxsj8uD7/dhw7W0KkaWlmvW9QmAWDl/xOtVgBOE5Vn3pA9rKDQK4G3//vX58MW/edqL0L0iPeaGVjIU+hXi+HMa7INLfhfB6sKajK6S3SQ5SoG1ly4oc7UuoY87r85U0V3sfvDT2XwLDx+xsqZnO/3AhIzVHqfBz1AcKnmDJZcoPvLWeX501utCyfjGMeS8jTCYMVWoAkFjKdNuUs+IpbYNf5UYHzYME5uLqv1AXUEKhm+ke2Kudcf3dIUVR63uXXQNRzI3Bbf/H08f/oluA/m/12fZIbUS2q01e8WEGxOF8m1TUWTlDGgmQKl1hvYaUa85iuBYmgHouj5R913j0vnBXVL4zhrUNYpqaXzMZ7yJGecdWdFHg8ezUyBtx4tH/HMonWP1uwguaWqmmAHpD86MxND49XiCDoaQku3IxAnWCFqPRdPkdyZ3lRVWpJyuL6V4X7ysXi/89g+YLlGI6bEgygyopHY8EEORX/JrlTmZzjfRaE0pNJqbtiOzM7sEmzk88wUAJwNvh7r+ANy8Tjz5qAeoe8pR7S4/Aovn5dMx20v0NrRPDjsKgABmxu55ex2CXX6pZKKwgEE2nhPA0Ze9U1eefm0p+3DLJf6wOh3pPA9hpUdcEdlPu+XGGNgFXp0a7jJTEodiFpZFNC+k="
#       FAEDER_PASSWORD
    - secure: "qJoGONuSA/4WxnxCZJuUuqZso5CIO8oHuzNARMO4mm/T3bvEA+ywmwzEtdCIqFeXuZZ/I3D4opxcuHfIKLinLjr2sMlLRUeRBno8ptD3qKZEp25+U7rDpsHual1eqXen4N9iCHjmH8LJWfvF2FfvR2J2CMrhQRZ1+bcx/rxH45oyLi2iCuUBt2oSLpS5j1ScRbHyVvpZj1yVYDh7LnD3DsZM2zLb1sobV5Cp7JNf2WJa97BSXmskLND9KU8NPLPUop78Zde1YcbpdyYaN+hHP86CNIUVAyZwQmo+dYe226WTBNu7MvTD3zEBDGZnmK92rRdwoEAv5brLwtg/1YMz3iX2aMhqZLhxa1ydJt1PqgNsKqzL4DgRF06BszpsbYqxdyPJ9lCjfVMUsGeSI/m9hZA2SOxCUzQKg5+O/Xyh27HRmZ1QcytcaREHEMHTeIsOJ4Am1NMu7erZG4Nqn+L0+T3DevJPJ+Q7GUwdbY0TlLBGPBjuXEQ3dP+glEUs1Cr9i7A3HRL++TUAtoPNvKDfD8JzT6zln2ylS7PSRmhyhrCnm90steQeHvsvBDwdrOf9pve9hCsQ1OXzCkfJRxhCYZUG/4vNH/4aMYjPItBpPpO3nPXcvrDyEVlbMXxZFqIIFD3iBxR5DvS2j5iqp2o13U2VWtZ97FmMGBX9MUmr+Qg="



notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Download Distribution Package Here:"
       - "https://rawgit.com/RuleWorld/bionetgen/master/.BioNetGen_Beta.html"
       - "Build details:  %{build_url} "
   
  
script:
  -  cd ./bng2
  - mkdir bindir_nfsim_atomizer
  - source .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate  --bindir ./bindir_nfsim_atomizer
  - source .dist_unix.sh


after_success:
#  The make clean step has been added to make_dist.pl
#  -  cd BioNetGen-2.3.0/Network3 && make clean && cd ../../.. && mkdir dist && mv ./bng2/BioNetGen-2.3.0 ./dist/$TRAVIS_OS_NAME && cd dist && tar cf $TRAVIS_OS_NAME.tar $TRAVIS_OS_NAME && gzip $TRAVIS_OS_NAME.tar && rm -rf $TRAVIS_OS_NAME && cd ..


