os:
  - linux
  - osx


language: c++
sudo: false


env:
  global:
#       FTP_USER_0
    - secure: "hnGm8cr+5yBAl4k4XUyMpmiePMDp6JJPOBcZYcDOdmCjALkdtC1OVUmLhe6fbCAZ/efF4P6qBid/S3Qk/OjfUMMYAxhpqTMx3IYFnxktUR2mRlmua9zGbCAGRQ7eF7EcdpwIHv5qUlHmb8NTqD6T5GHL+822pmcQE/mPZkyvuqjFOVYO88fDRF87jIYmIUQRqCCUSkn2OVKx9l58G33H8T3qVyibykJyerSSgZx3CxOtmSb8cn1n6c+APCFL/ACiegskd5GdcZsBZXqCo+EgBe2z4iaLeo+9Blopi3hJln5rT4xmnDbJTdGLUp0IarXrZWY/qibT7X74aoyfW575AFqWRkIhRvCKtAjdxbru6ESwWdbcnXUrg8lClxoLJMq88GXuyiqT2dukrBGVe7Oma0gv5AleOOlX0sC2WhX+Zu2WtUZud0vbxGGdCqWXVZdyRUiGXaZI89imonMBQvKso3vobQFdCM6AdsyM+Dn5eKlifYyerfjZS1IYgPYYLGdjBU7aMvacavyxMHR2mMtS8ZH0SgrhV1VoxoBi7SdBPsUOo7oquQzxkSzopE5OYy/cIaK4fiaQlxmP+zQg87pvQmptaYigHLTntJ4UkQExgjOFuYH08I09plYmShrVV1jQXIIEvOKF473B7sKJhro2xqbXu+h8wl90b/ck7XkrPhM="
#       FTP_USER_1
    - secure: "jDCJH/4LWXIaYrbpOyoBmdg1YTvfqaUhD+mWbHL6SKYKdTEG+qYO5f0sz8LXcEcZYTYc5SP/2jS9wMO5eOFv+m8yJIqkd0gwc1rvwSO/vFhgISEVw2CCK+12edtFWrSi92eKWwqy+6RMmp6uAIYjZuqXTm+LjXOsxdBfVcuCve7UAJjRzTGEFKKeiC+fZZxZxG6LQ+BwDzJ2lElyB4CSVO4Z0euoW+p5aoT6zWsyRPL9STY+mqaAJt9pl3EQ+Sf3fkyJx7mIjm4VDmmfN8Dg8xdsqJwr6GZQMisEATewWInsGI+rvtDchG5ojWGgnY1/D2on5Cp8D+BRQXBd0e1PrWC6XTgifATh/mB0iKK9eCUph1vqTa52Kga9htaCJ0ZEfQRI0DhXtbgmmcEhxMjl35kbwIaLoT69UCU0S1dRLtqoMHUu2rC/76stjVaB+Dq7DiNjYfPnsY1g7+9hNgjWUJz3y9VIlD/YmXpcZI5VJIF+OT3k/FTqFh5pG3hjBaUEsVp5VLoV5PvQ9GfThVKWSLYrdWJ1oTIUZjcEfU1nxV6+N61QhYk9x+A+L3bOO5gfsLfps6J4esbbzHdxQAOD7+rBy6w8o3YyrDWADyZ/sa3xI79qjGFmKv9/81butkyo31HbYgDqD22jp8EbFUEvClPB+zPLQzIJF7jOjtU2a9c="    
#       FTP_PASSWORD
    - secure: "k4LDmoek9euxvKB39fBugp4f4M4hFtuNfC9HL9ei6WcgnD5An0XJP4+nW4qJLpPYnNtdrPlmP21qv2UTO6CijKjuHhsrM0Bbf4vyI1I+QAoxY/mc5iyYTSe+CtHQY/GznsZLzfEtkxE8wGc028/RSof1sn1y2M6bMDw9J5RQvUS8WYmTORcdzDppSWwjMbkofTTabyhrnz+5Eg8xKW7Az1CwIpOGTXq2BDMkMGfwmMRWcKrPKmuHLX31mX7FFiDoKR72I/T8cKSwPcZJ8jR7bXWuRM9rsX/kEQTybM8PQD9COxIV5tdmzJ09asCCeAIDq7VC+TCpvfieKCOZH9wz6sqfLbG8NIAcakcF2/pb2vb5L8c1yIgrUpbSjTzD/+IpMzdkoHoAK28BJETIZOTQf4vykA5gxTQoeO6l3Yt4cWagnL31Pm1bjAt+zz441EStNiXk3S7oyjwgb7TM571BjXAZ8UXr+OfLMl4gSWtNiEKXjq+KmYG0EoMkG6AM4r3IIFQKj5CJs8BWl3l3gI4fdSx7sy12pMqVMSxeQLwGwabAHZnOjlPF1sTzi8t5GdkHsZHT6DTMkiEoOkt6L+lcUsm3SQvju+QfALJvlbHjq1A8TJLPZjsOjWnC5/u9Fe8ysICA0ie4DzJoKoL9ol361+HeZ7C4OGhX2i9I6wP/2D8="

#       FAEDER_USER
    - secure: "stAZ+q/O0t3Js0IlyuNId53vGcDGZkvwDIXlXixB/OCqcE5t4lb+WT0pZtzs46wi9+0R2rXwyxmU1qpZkBGdPGJN4BtPTjf19X/CFLn5uBPV4fwgRQrnmYS8ShSnzUHziK9XZ91TUP8VkMJnwwLmmNwBUq5/DB94NdE7vhJ/zQIKIB6vVJpFQTMyHDPzjrRQNcrgBBso+/+hXpgr6wKvbTV+714PoQTr3+CsUhS5IPJUCeOMCo+9CGU6qbprDPMgkmDkQYTSHqz6gNW5zgEkX2IW8RJmthV/yhaw3bu+m7q8ZheD/fv3cjkUbr6qL4FdO1yz8TbKTbyY8bApEA7yDss2BwATHmKwC3x7FciksRiU3GdV7gumsjpq2Fn+7rxNYNmKDRgIq0CnoPKw4AUM89bFszeRdw+RthYzEScNkFWO++CtAtbhL8/brow1Ck6/Fl/W4/LaDdrZiY1REnHCBaf7DYIj8cF8ObomT0lagtXEKd0jwbqRqE7vCxahZPucvFD3cDHynfzCgGuSvq2vTgeCL1ndQFAL4AbhaHFWD9SjVhks9wGwZu9w0/N/dOy2VQJahkuzdSJqaobYFCLitv2BYanY5PCdNVI3ixOhXqHVWQ8ScubMXhGShgQcf3U8b5I+UCnRwecOp4l6JrrmSfvDxFrQCMrAar7WtihGxI8="
#       FAEDER_PASSWORD
    - secure: "Blt7cHDdvHfv15MOVFA66/N++Z3PmXsdzra5JCpP0SFMHdOCka6QlP7VUTBSylDO3KF1UJqDiqUEI8aQUWGKtBZw+smVE2Ycvf7rSOgWrS51qIbr2QvuQKRaki6bhvBY2UGCF1R+X0KAZcELnwN+bWgiSxhsK2aJTDy9uwC7ZGok+lsYFD3OrA/A5BDUo4EdALyBb7cJlM5rpv67grVfQDMP97M/lipARhWPp6xIey+Omz9nE9HBPWHwd9cTEwjw5uKVIZxAqyjal7NPakZ90v9BdtKQPFyzC8JhIF7omJUzBACAHpLvHZHAbCxsF2fKGsjn7J6tX5sp5N53jLjL6V8+LSbkKkrT0y+ZeRFLLMQQlOrHtApgeM3onpESgVrMzCWO0HA7eQzrq4dwemQYiy92PpsUjqo5lBByo6ecmrtgbxpRSCrMXnHA1Ll3MUbxe/0geGGcvfkqR1mUHNJX/xcrIWl31vGCM8WQkI7QKoq9is97U9fK6aLHHhTp4Wj5N8bX13EDOTrdUECb80DqnB2tLl+jo0OtA0X2yIM7oONX9ofUAxwU4oJtj4FVLyO32gR8oniweAnHJs7H4FDW//N37w53W8Uch7ioy+wrifmPgrML00yarMwNzXWdg3zJasaXa/zU80JmwbmgufNOUI9M5rYT1u1m0Z0GpqrQzaU="



notifications:   
   slack: 
     rooms:
       - faederlab:l0waIGp58v8ZV74N7QmXGoWs      
     template:
       - "BioNetGen build: %{result} in %{duration}"
       - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)    Author: %{author}"
       - "Download Distribution Package Here:"
       - "https://rawgit.com/RuleWorld/bionetgen/master/BNG_Build_Instructions.html"
       - "Build details:  %{build_url} "
   
  
script:
#  - curl -v --ftp-ssl -u $FAEDER_USER:$FAEDER_PASSWORD ftp://ftp.box.com/BioNetGen_Beta
  - curl -v -u $FAEDER_USER:$FAEDER_PASSWORD ftp://ftp.box.com/BioNetGen_Beta
  - cd ./bng2
  - mkdir bindir_nfsim_atomizer
  - source .get_nfsim_atomizer.sh  ./bindir_nfsim_atomizer
  - cd ./Network3 && mkdir -p m4 && cd .. && perl make_dist.pl --build --validate  --bindir ./bindir_nfsim_atomizer
  - source .dist_unix.sh


after_success:
#  The make clean step has been added to make_dist.pl
#  - cd BioNetGen-2.3.0/Network3 && make clean && cd ../../.. && mkdir dist && mv ./bng2/BioNetGen-2.3.0 ./dist/$TRAVIS_OS_NAME && cd dist && tar cf $TRAVIS_OS_NAME.tar $TRAVIS_OS_NAME && gzip $TRAVIS_OS_NAME.tar && rm -rf $TRAVIS_OS_NAME && cd ..


